import type { NextPage, GetServerSidePropsContext } from "next";
import Head from "next/head";
import BeerInfo from "../../components/beer-info/BeerInfo";
import { getAllBeers } from "../../data";
import type { Beer } from "../../types";

interface BeerProps {
  beer: Beer;
}

const BeerById: NextPage<BeerProps> = ({ beer }) => {
  return (
    <div>
      <Head>
        <title>{beer.name} beer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BeerInfo beer={beer} />
    </div>
  );
};

export async function getStaticPaths() {
  const allBeers = await getAllBeers();
  return {
    paths: allBeers?.map((beer) => ({ params: { id: beer.id.toString() } })),
    fallback: false, // false or 'blocking'
  };
}

export async function getStaticProps(
  context: GetServerSidePropsContext<{ id: string }>
) {
  const { params } = context;
  const allBeers = await getAllBeers();
  const beer = allBeers?.find(
    ({ id }) => id === parseInt(params?.id ?? "", 10)
  );
  if (!beer) return { notFound: true };
  return { props: { beer } };
}

export default BeerById;
