import type { NextPage } from "next";
import Head from "next/head";
import { getInitialBeers } from "../data/getInitialBeers";
import { Beer } from "../types";

interface AboutProps {
  beers: Beer[];
}

// eslint-disable-next-line no-unused-vars
const About: NextPage<AboutProps> = ({ beers }) => {
  return (
    <div>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Aboutpage
    </div>
  );
};

export async function getServerSideProps() {
  const beers = await getInitialBeers();
  return { props: { beers } };
}

export default About;
