import type { NextPage } from "next";
import Head from "next/head";
import BeersGrid from "../components/beers-grid";
import { getInitialBeers } from "../data";
import { Beer } from "../types";

interface HomeProps {
  beers: Beer[];
}

const Home: NextPage<HomeProps> = ({ beers }) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BeersGrid beers={beers} />
    </div>
  );
};

export async function getServerSideProps() {
  const beers = await getInitialBeers();
  return { props: { beers } };
}

export default Home;
