import type { NextPage } from "next";
import Head from "next/head";
import { getInitialBeers } from "../data/getInitialBeers";
import { Beer } from "../types";

interface HomeProps {
  beers: Beer[];
}

const Home: NextPage<HomeProps> = ({}) => {
  return (
    <div>
      <Head>
        <title>home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Homepage
    </div>
  );
};

export async function getServerSideProps() {
  const beers = await getInitialBeers();
  return { props: { beers } };
}

export default Home;
