import type { NextPage } from "next";
import Head from "next/head";
import BeersGrid from "../components/beers-grid/";
import Filter from "../components/filter";
import { getBeers } from "../data";
import useBeers from "../hooks/useBeers";
import { Beer, FiltersOptions } from "../types";

interface HomeProps {
  initialBeers: Beer[];
}

// agregar filtros
const Home: NextPage<HomeProps> = ({ initialBeers }) => {
  const {
    beers,
    loadingMore,
    refetching,
    hasNextPage,
    error,
    loadMore,
    refetch,
  } = useBeers(initialBeers);

  const handleFiltersChange = (newFilters?: FiltersOptions) => {
    refetch(newFilters);
  };

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Filter loading={refetching} onFiltersChange={handleFiltersChange} />
      <BeersGrid
        beers={beers}
        disabled={error}
        loading={loadingMore}
        loadMore={loadMore}
        hasNextPage={hasNextPage}
      />
    </div>
  );
};

export async function getServerSideProps() {
  const initialBeers = await getBeers();
  if (!initialBeers) return { notFound: true };
  return { props: { initialBeers } };
}

export default Home;
